#!/usr/bin/env python3
"""
Group the 128 PE exports by feature prefix and verb, and emit a markdown
table that becomes the heart of docs/03-exports-catalog.md.

Rules
-----
1. Split the name on underscores.
2. The "namespace" prefix is the longest known prefix that matches.
   Currently the two namespaces present in bambu_networking.dll are
   `bambu_network` and `ft_tunnel`, plus anything unrecognised goes to
   `<other>`.
3. The remaining suffix is then grouped by its first significant verb/noun
   so that families like `*_login_*`, `*_user_*`, `*_print_*` cluster
   visually.

Usage
-----
    python3 scripts/categorize_exports.py            # writes both outputs
    python3 scripts/categorize_exports.py --markdown # markdown only to stdout
"""
from __future__ import annotations
import argparse
import re
import sys
from collections import defaultdict, OrderedDict
from pathlib import Path

EXPORTS_FILE = Path("output/exports.txt")
OUT_MD = Path("output/exports_categorized.md")
OUT_JSON = Path("output/exports_categorized.json")

# Namespaces in the public ABI of bambu_networking.dll. `ft` covers
# ft_abi_version, ft_free, ft_job_*, ft_tunnel_* (a single shared namespace
# even though the suffix split looks like multiple subsystems at first glance).
NAMESPACES = ("bambu_network", "ft")

# Family keywords - order matters; first match wins.
# Anything not matched falls back to `misc`.
FAMILY_RULES = [
    ("auth/session",   r"login|logout|token|user|bind|change_user|sign|password|verify"),
    ("device",         r"device|printer|machine|connect_printer|search_pid"),
    ("print/job",      r"print|job|task|gcode|slice|model|order|build_plate"),
    ("network/io",     r"send|recv|receive|publish|subscribe|message|msg|push|pull|http|url|request|response"),
    ("transport/tcp",  r"tunnel|tcp|udp|socket|stream|websocket"),
    ("cloud/storage",  r"cloud|upload|download|file|cdn|bucket|storage"),
    ("config/state",   r"config|setting|option|param|state|status|flag|enable|disable"),
    ("lifecycle",      r"init|shutdown|start|stop|create|destroy|free|reset|begin|end|open|close"),
    ("logging/debug",  r"log|debug|trace|err|error|report"),
    ("callback",       r"cb|callback|handler|listener|event"),
    ("query/getter",   r"get_|is_|has_|query|fetch|check"),
    ("setter",         r"set_"),
]


def load_exports(path: Path):
    rows = []
    for line in path.read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 3:
            continue
        ord_, rva, name = parts[0], parts[1], " ".join(parts[2:])
        rows.append((int(ord_), int(rva, 16), name))
    return rows


def namespace_of(name: str) -> tuple[str, str]:
    for ns in NAMESPACES:
        if name.startswith(ns + "_"):
            return ns, name[len(ns) + 1:]
    return "<other>", name


def family_of(suffix: str) -> str:
    for fam, pattern in FAMILY_RULES:
        if re.search(pattern, suffix):
            return fam
    return "misc"


def build_groups(exports):
    """Return {namespace: {family: [(ord, rva, name, suffix)]}}."""
    grouped: dict[str, dict[str, list]] = defaultdict(
        lambda: defaultdict(list)
    )
    for ord_, rva, name in exports:
        ns, suffix = namespace_of(name)
        fam = family_of(suffix)
        grouped[ns][fam].append((ord_, rva, name, suffix))
    # Deterministic ordering
    ordered = OrderedDict()
    for ns in sorted(grouped.keys()):
        fams = grouped[ns]
        ordered[ns] = OrderedDict(
            sorted(fams.items(), key=lambda kv: (kv[0] == "misc", kv[0]))
        )
        for fam in ordered[ns]:
            ordered[ns][fam].sort(key=lambda r: r[2])
    return ordered


def render_markdown(grouped) -> str:
    lines = []
    lines.append("# Exports of `bambu_networking.dll`, by namespace and family")
    lines.append("")
    lines.append(
        "Auto-generated by `scripts/categorize_exports.py`. Each row is "
        "`ordinal | RVA | export name`. The family column is a heuristic "
        "guess based on the suffix; refine by hand as we learn more."
    )
    lines.append("")
    # Summary table
    lines.append("## Summary")
    lines.append("")
    lines.append("| Namespace | Count | Families |")
    lines.append("|---|---:|---|")
    for ns, fams in grouped.items():
        total = sum(len(rows) for rows in fams.values())
        fam_summary = ", ".join(f"`{f}`({len(r)})" for f, r in fams.items())
        lines.append(f"| `{ns}` | {total} | {fam_summary} |")
    lines.append("")
    # Per-namespace tables
    for ns, fams in grouped.items():
        lines.append(f"## Namespace `{ns}`")
        lines.append("")
        for fam, rows in fams.items():
            lines.append(f"### {fam} ({len(rows)})")
            lines.append("")
            lines.append("| Ord | RVA | Name |")
            lines.append("|---:|---|---|")
            for ord_, rva, name, _ in rows:
                lines.append(f"| {ord_} | `0x{rva:08x}` | `{name}` |")
            lines.append("")
    return "\n".join(lines) + "\n"


def render_json(grouped) -> str:
    import json
    out = {}
    for ns, fams in grouped.items():
        out[ns] = {}
        for fam, rows in fams.items():
            out[ns][fam] = [
                {"ordinal": o, "rva": r, "name": n, "suffix": s}
                for o, r, n, s in rows
            ]
    return json.dumps(out, indent=2, sort_keys=True) + "\n"


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--markdown", action="store_true",
                    help="emit markdown to stdout instead of writing files")
    args = ap.parse_args(argv[1:])
    exports = load_exports(EXPORTS_FILE)
    grouped = build_groups(exports)
    if args.markdown:
        sys.stdout.write(render_markdown(grouped))
        return
    OUT_MD.write_text(render_markdown(grouped))
    OUT_JSON.write_text(render_json(grouped))
    total = sum(len(r) for fams in grouped.values() for r in fams.values())
    print(f"Categorized {total} exports across {len(grouped)} namespaces.")
    print(f"  markdown -> {OUT_MD}")
    print(f"  json     -> {OUT_JSON}")


if __name__ == "__main__":
    main(sys.argv)
